const fs = require('fs');
const enFiles = fs.readdirSync('blog').filter(f => f.endsWith('.html') && !f.startsWith('_'));
const jaFiles = fs.readdirSync('ja/blog').filter(f => f.endsWith('.html') && !f.startsWith('_'));
const koFiles = fs.readdirSync('ko/blog').filter(f => f.endsWith('.html') && !f.startsWith('_'));
const enSlugs = new Set(enFiles.map(f => f.replace('.html','')));
const jaSlugs = new Set(jaFiles.map(f => f.replace('.html','')));
const koSlugs = new Set(koFiles.map(f => f.replace('.html','')));
const koContentKo = koFiles.filter(f => f.includes('-content-ko'));
const koRegular = koFiles.filter(f => !f.includes('-content-ko'));
console.log('EN blog posts:', enFiles.length);
console.log('JA blog posts:', jaFiles.length);
console.log('KO blog posts:', koFiles.length);
console.log('KO -content-ko variants:', koContentKo.length, koContentKo);
console.log('');
console.log('Missing in JA (present in EN):');
[...enSlugs].filter(s => !jaSlugs.has(s)).forEach(s => console.log('  ', s));
console.log('');
console.log('Missing in KO (present in EN):');
[...enSlugs].filter(s => !koSlugs.has(s)).forEach(s => console.log('  ', s));
console.log('');
console.log('Present in KO but not in EN:');
[...koSlugs].filter(s => !enSlugs.has(s)).forEach(s => console.log('  ', s));
